[package]
name = "camera"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
dotenvy = { workspace = true }
tokio = { workspace = true }
common = { path = "../common" }
serde_json = { workspace = true }
opencv = "0.94.2"
